% Processing of diffusion MRI data using DSI Studio, converting DWI to 
% SRC format, reconstructing diffusion data with GQI, and performing fiber 
% tractography with ROI-based connectivity analysis.
clc;clear;close all;
subG = {'sub-0001', 'sub-0002', 'sub-0003', 'sub-0004', 'sub-0005', ...
    'sub-0008', 'sub-0009', 'sub-0010', 'sub-0011', ...
    'sub-0012', 'sub-0013', 'sub-0014', 'sub-0015', 'sub-0016', ...
    'sub-0017', 'sub-0019', 'sub-0020', 'sub-0021', 'sub-0022', ...
    'sub-0023', 'sub-0028', 'sub-0031', 'sub-0033', ...
    'sub-0035', 'sub-0036', ...
    'sub-0050',  ...
    'sub-0067', 'sub-0074', ...
    'sub-0087', 'sub-0089', 'sub-0092', 'sub-0093', 'sub-0094'};
% ===== DSI Studio Executable Path =====
dsistudio = 'C:\dsistudio\dsi_studio_win_2024May17\dsi_studio.exe';
% ===== Data Path Configuration =====
DSIpath = 'step2_fiberTrack\DSI';
% ==== Main Processing Loop =====
for nS = 1:length(subG)
    subID = subG{nS};
    % ---- File Path Construction ----
    dsi = fullfile(DSIpath, subID, [subID, '_ses-001_run-001_space-ACPC_desc-preproc_dwi.nii.gz']);
    btable = fullfile(DSIpath, subID, [subID, '_ses-001_run-001_space-ACPC_desc-preproc_dwi.b_table.txt']);
    T1w = fullfile(DSIpath, subID, [subID, '_ses-001_space-ACPC_desc-preproc_T1w.nii.gz']);
    roi = fullfile(DSIpath, subID, [subID, '_space-ACPC_roi.nii']);
    % ---- Fiber Tractography & Connectivity ----
    gqi = fullfile(DSIpath, subID, [subID, '_ses-001_run-001_space-ACPC_desc-preproc_dwi.nii.gz.src.gz.gqi.1.25.fib.gz']);
    fiberTractOP = fullfile(DSIpath, subID);
    fiberTract = [dsistudio, ' --action=trk --source=', gqi, ...
        ' --output=' fiberTractOP, ...
        ' --method=0 --fiber_count=5000000', ...'
        ' --turning_angle=90 --min_length=2 --max_length=250', ...
        ' --other_slices=', T1w, ...
        ' --connectivity=', roi, ...
        ' --connectivity_type=pass', ...
        ' --connectivity_value=count,ncount,ncount2,mean_length,qa', ...
        ' --connectivity_threshold=0'];
    system(fiberTract);
end