% Mapping each contact to atlas.
clc; clear; close all; addpath z_toolbox;
addpath 'H:\project_manger\xlz_toolbox\fieldtrip-20231220';
ft_defaults;
subG = {'sub-0001', 'sub-0002', 'sub-0003', 'sub-0004', 'sub-0005', ...
                'sub-0007', 'sub-0008', 'sub-0009', 'sub-0010', 'sub-0011', ...
                'sub-0012', 'sub-0013', 'sub-0014', 'sub-0015', 'sub-0016', ...
                'sub-0017', 'sub-0019', 'sub-0020', 'sub-0021', 'sub-0022', ...
                'sub-0023', 'sub-0028', 'sub-0029', 'sub-0031', 'sub-0033', ...
                'sub-0034', 'sub-0035', 'sub-0036', 'sub-0039', 'sub-0046', ...
                'sub-0047', 'sub-0050', 'sub-0052', 'sub-0054', 'sub-0062', ...
                'sub-0063', 'sub-0066', 'sub-0067', 'sub-0074', 'sub-0077', ...
                'sub-0087', 'sub-0089', 'sub-0092', 'sub-0093', 'sub-0094', ...
                'sub-0113', 'sub-0115'};
% ===== JHU White Matter Atlas Configuration =====
JHUlabels = {'none', ... % 0
                        'none', 'none', 'CorCalT', 'CorCalT', 'CorCalT', ... % 1-5
                        'FornixT', 'CorSpiT','CorSpiT', 'MedLemT', 'MedLemT', ...
                        'none', 'none', 'none', 'none', 'none', ...
                        'none', 'IntCapT', 'IntCapT', 'IntCapT', 'IntCapT', ...
                        'IntCapT', 'IntCapT', 'CorRadT', 'CorRadT', 'CorRadT', ...
                        'CorRadT', 'CorRadT', 'CorRadT', 'ThaRadT', 'ThaRadT', ...
                        'SagStrT', 'SagStrT', 'ExtCapT', 'ExtCapT', 'CingT', ...
                        'CingT', 'CingT', 'CingT', 'none', 'none', ...
                        'SupLonF', 'SupLonF', 'IntCapT', 'IntCapT', 'FroOccF', ...
                        'FroOccF', 'UncF', 'UncF', 'CorCalT', 'CorCalT', ...
                        'SupFroB', 'SupFroB', 'MidFroB', 'MidFroB', 'InfFroB', ...
                        'InfFroB', 'PreCenB', 'PreCenB', 'PoCenB', 'PoCenB', ...
                        'SupParB', 'SupParB', 'ParTempB', 'ParTempB', 'TempB', ...
                        'TempB', 'OccB', 'OccB'};
JHUidxs = 0:68;
% ===== Yeo7 Functional Network Atlas Configuration ====
Yeo7Labels = {'none', ... % 0
                        'Vis', 'SomMot', 'DorsAttn', 'DorsAttn', 'DorsAttn', ...
                        'SalVentAttn', 'SalVentAttn', 'SalVentAttn', 'SalVentAttn',  'SalVentAttn', ...
                        'Limbic', 'Limbic', 'Cont' 'Cont',  'Cont', ...
                        'Cont', 'Cont', 'Cont', 'Cont', 'Cont', ...
                        'Cont', 'DM', 'DM', 'DM', 'DM', ...
                        'DM', 'Vis', 'SomMot', 'DorsAttn', 'DorsAttn', ...
                        'DorsAttn', 'SalVentAttn', 'SalVentAttn', 'SalVentAttn', 'SalVentAttn', ...
                        'SalVentAttn', 'SalVentAttn', 'Limbic', 'Limbic', 'Cont', ...
                        'Cont', 'Cont', 'Cont', 'Cont', 'Cont', ...
                        'Cont', 'DM', 'DM', 'DM', 'DM', ...
                        'DM'};
Yeo7_51_Labels = {'none', ... % 0
                        'Vis', 'SM', 'DA.Post', 'DA.FEF', 'DA.PrCv', ...
                        'SA.PO', 'SA.TO', 'SA.FOI', 'SA.PFCl',  'SA.Med', ...
                        'Lim.OFC', 'Lim.TP', ...
                        'C.Par', 'C.Temp',  'C.PFCd',  'C.PFCl', ...
                        'C.OFC', 'C.PFCv', 'C.pCun', 'C.Cing', 'C.PFCmp', ...
                        'D.Par', 'D.Temp', 'D.PFC', 'D.pCun', 'D.PHC', ...
                        'Vis', 'SM', 'DA.Post', 'DA.FEF',  'DA.PrCv', ...
                        'SA.TOP', 'SA.PrC', 'SA.FOI', 'SA.PFCv', 'SA.PFCl', 'SA.Med', ...
                        'Lim.OFC', 'Lim.TP', ...
                        'C.Par', 'C.Temp', 'C.PFCv', 'C.PFCl', ...
                        'C.pCun', 'C.Cing', 'C.PFCmp', ...
                        'D.Par', 'D.Temp', 'D.PFCv', 'D.PFCdm', 'D.pCun'};
Yeo7idxs = 0:51;
% subcortex region
ASEGlabels = {'Accumbens', 'Amygdala', 'Caudate', 'Hippocampus', ...
                        'Pallidum', 'Putamen', 'Thalamus', 'VentralDC', 'White', 'Cortex'};
ASEGlabelsA = {'Acc', 'Amy', 'Cau', 'Hip', 'Pal', 'Put', 'Tha', 'VDC', 'White', 'Cortex'};
% load atlas image
JHU = ft_read_mri(fullfile('atlas', 'rICBM_DTI_81_WMPM_60p_FMRIB58.nii.gz'));
Yeo7 = ft_read_mri(fullfile('atlas', ...
    'Yeo2011_7Networks_N1000.split_components.FSL_MNI152_FreeSurferConformed_1mm.nii.gz'));
rawSEEGPath = 'E:\seegDataset_xuanwu\step7_ageOver16_awakeSEEG_300s_miniPrep';
bpSEEGPath = 'step1_AwakeSEEG_BPfiltering_Age16Up';
% ===== Main Processing Loop =====
for ns = 1:length(subG) % Iterate through subjects
    subID = subG{ns};   % Current subject ID
    load(fullfile(rawSEEGPath, subID, [subID, '_ROI-3mm_elecLocation.mat'])); 
    load(fullfile(bpSEEGPath, subID, [subID, '_task-rest_run-01_ieeg_miniPrep_BPfiltering.mat']));
    % Process each electrode contact
    contAnat = [];
    for nC = 1:size(elecInfo, 1)
        cName = elecInfo.Channel{nC};
        % Store contact information
        contAnat.label{nC, 1} = cName;
        contAnat.World{nC, 1} = str2num(elecInfo.World{nC});
        contAnat.MNI{nC,1} = str2num(elecInfo.MNI{nC});
        % Extract ASEG region without hemisphere indicators
        ASEG = elecInfo.ASEG{nC};
        contAnat.ASEG{nC, 1} = 'none';
        a = f_strsplit(ASEG, ' L'); a = a{1};
        a = f_strsplit(a, ' R'); a = a{1};
        b = strcmp(a, ASEGlabels);
        if any(b)
            contAnat.ASEG{nC, 1} = ASEGlabelsA{b==1};
        end
        % Determine left/right hemisphere based on atlas labels
        if contains(ASEG, ' L') 
            contAnat.LR{nC, 1} = 'L';
        elseif contains(ASEG, ' R')
            contAnat.LR{nC, 1} = 'R';
        else
            contAnat.LR{nC, 1} = 'none';
        end
    end
    contAnat = struct2table(contAnat);
    % Cortex/WhiteMatter/Subcortex
    for nC = 1:size(contAnat, 1)
        ASEG = contAnat.ASEG{nC};
        if strcmp(ASEG, 'Cortex')
            contAnat.CWS{nC} = 'Cortex';
        elseif strcmp(ASEG, 'White')
            contAnat.CWS{nC} = 'White';
        elseif strcmp(ASEG, 'none')
            contAnat.CWS{nC} = 'none';
        else
            contAnat.CWS{nC} = 'Subcortex';
        end
    end
    % Mapping contact to JHU atlas
    for nC = 1:size(contAnat, 1)
        CWS = contAnat.CWS{nC};
        MNI = contAnat.MNI{nC};
        contAnat.JHU{nC} = 'none';
        if strcmp(CWS, 'White')
            roiVoxelXYZ = f_xyz2roi(MNI, JHU, 2);
            [atlasName, p, roiAtlasIdx] = f_roi2atlas(roiVoxelXYZ, JHU, JHUidxs, JHUlabels);
            contAnat.JHU{nC} = atlasName;
        end
    end
    % Mapping contact to Yeo-7 network atlas
    for nC = 1:size(contAnat, 1)
        CWS = contAnat.ASEG{nC};
        MNI = contAnat.MNI{nC};
        contAnat.Yeo7_51{nC} = 'none';
        contAnat.Yeo7{nC} = 'none';
        if strcmp(CWS, 'Cortex')
            roiVoxelXYZ = f_xyz2roi(MNI, Yeo7, 2);
            [atlasName, p, roiAtlasIdx] = f_roi2atlas(roiVoxelXYZ, Yeo7, Yeo7idxs, Yeo7Labels);
            contAnat.Yeo7{nC} = atlasName;
            contAnat.Yeo7_51{nC} = Yeo7_51_Labels{roiAtlasIdx+1};
            contAnat.Yeo7_51_idx{nC} = roiAtlasIdx;
        end
    end
    % ===== Save Processed Data =====
    saveFolder = fullfile('step1_AwakeSEEG_BPfiltering_Age16Up', subID);
    mkdir(saveFolder);
    saveName = [subID, '_ROI-3mm_contactAnatomy.mat'];
    save(fullfile(saveFolder, saveName), 'contAnat');
end
