% Computes Euclidean distance matrices for electrode contacts in both 
% world coordinates and MNI standard space. 
clc; clear; close all;
subG = {'sub-0001', 'sub-0002', 'sub-0003', 'sub-0004', 'sub-0005', ...
            'sub-0007', 'sub-0008', 'sub-0009', 'sub-0010', 'sub-0011', ...
            'sub-0012', 'sub-0013', 'sub-0014', 'sub-0015', 'sub-0016', ...
            'sub-0017', 'sub-0019', 'sub-0020', 'sub-0021', 'sub-0022', ...
            'sub-0023', 'sub-0028', 'sub-0029', 'sub-0031', 'sub-0033', ...
            'sub-0034', 'sub-0035', 'sub-0036', 'sub-0039', 'sub-0046', ...
            'sub-0047', 'sub-0050', 'sub-0052', 'sub-0054', 'sub-0062', ...
            'sub-0063', 'sub-0066', 'sub-0067', 'sub-0074', 'sub-0077', ...
            'sub-0087', 'sub-0089', 'sub-0092', 'sub-0093', 'sub-0094', ...
            'sub-0113', 'sub-0115'};
seegPath = 'step2_SEEG_TCAR_BPF';
elecPath = 'step1_AwakeSEEG_BPfiltering_Age16Up';
for nS = 1:length(subG)
    subID = subG{nS};
    % Load preprocessed SEEG data and anatomical info of electrode contacts
    iEEGfileDir = dir(fullfile(seegPath, subID, [subID, '_task-rest_run-*_TCAR_BPF.mat']));
    load(fullfile(iEEGfileDir(1).folder, iEEGfileDir(1).name));
    load(fullfile(elecPath, subID, [subID, '_ROI-3mm_contactAnatomy.mat']));
    % --- Match Electrode Labels & Extract Coordinates ---
    label = data.label;
    coorWorld = []; coorMNI = [];
    for nC1 = 1:length(label)
        a = strcmp(label{nC1}, contAnat.label);
        coorWorld(nC1, :) =  contAnat.World{a==1};
        coorMNI(nC1, :) =  contAnat.MNI{a==1};
    end
    % --- Compute Euclidean Distance
    DistanceWorld = (coorWorld(:, 1) - coorWorld(:, 1)').^2 + ...
                    (coorWorld(:, 2) - coorWorld(:, 2)').^2 + ...
                    (coorWorld(:, 3) - coorWorld(:, 3)').^2;
    DistanceWorld = sqrt(DistanceWorld);
    DistanceMNI = (coorMNI(:, 1) - coorMNI(:, 1)').^2 + ...
                  (coorMNI(:, 2) - coorMNI(:, 2)').^2 + ...
                  (coorMNI(:, 3) - coorMNI(:, 3)').^2;
    DistanceMNI = sqrt(DistanceMNI);
    % --- Save Results ---
    savefolder = 'step2_channelDistance'; mkdir(savefolder);
    savename = [subID, '_EuclideabDistanceMatrix.mat'];
    save(fullfile(savefolder, savename), 'DistanceWorld', 'DistanceMNI');
end